/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccesEtConfidentialiteRouteImport } from './routes/acces-et-confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as RegarderSlugRouteImport } from './routes/regarder.$slug'
import { Route as TitreSlugRouteImport } from './routes/titre.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTitresIdRouteImport } from './routes/_authenticated/admin/titres.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesEtConfidentialiteRoute = AccesEtConfidentialiteRouteImport.update({
  id: '/acces-et-confidentialite',
  path: '/acces-et-confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RegarderSlugRoute = RegarderSlugRouteImport.update({
  id: '/regarder/$slug',
  path: '/regarder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TitreSlugRoute = TitreSlugRouteImport.update({
  id: '/titre/$slug',
  path: '/titre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTitresIdRoute =
  AuthenticatedAdminTitresIdRouteImport.update({
    id: '/admin/titres/$id',
    path: '/admin/titres/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces-et-confidentialite': typeof AccesEtConfidentialiteRoute
  '/auth': typeof AuthRoute
  '/films': typeof FilmsRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/regarder/$slug': typeof RegarderSlugRoute
  '/titre/$slug': typeof TitreSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/titres/$id': typeof AuthenticatedAdminTitresIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces-et-confidentialite': typeof AccesEtConfidentialiteRoute
  '/auth': typeof AuthRoute
  '/films': typeof FilmsRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/regarder/$slug': typeof RegarderSlugRoute
  '/titre/$slug': typeof TitreSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/titres/$id': typeof AuthenticatedAdminTitresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acces-et-confidentialite': typeof AccesEtConfidentialiteRoute
  '/auth': typeof AuthRoute
  '/films': typeof FilmsRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/regarder/$slug': typeof RegarderSlugRoute
  '/titre/$slug': typeof TitreSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/titres/$id': typeof AuthenticatedAdminTitresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces-et-confidentialite'
    | '/auth'
    | '/films'
    | '/recherche'
    | '/series'
    | '/mon-compte'
    | '/regarder/$slug'
    | '/titre/$slug'
    | '/admin/'
    | '/admin/titres/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces-et-confidentialite'
    | '/auth'
    | '/films'
    | '/recherche'
    | '/series'
    | '/mon-compte'
    | '/regarder/$slug'
    | '/titre/$slug'
    | '/admin'
    | '/admin/titres/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acces-et-confidentialite'
    | '/auth'
    | '/films'
    | '/recherche'
    | '/series'
    | '/_authenticated/mon-compte'
    | '/regarder/$slug'
    | '/titre/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/titres/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesEtConfidentialiteRoute: typeof AccesEtConfidentialiteRoute
  AuthRoute: typeof AuthRoute
  FilmsRoute: typeof FilmsRoute
  RechercheRoute: typeof RechercheRoute
  SeriesRoute: typeof SeriesRoute
  RegarderSlugRoute: typeof RegarderSlugRoute
  TitreSlugRoute: typeof TitreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces-et-confidentialite': {
      id: '/acces-et-confidentialite'
      path: '/acces-et-confidentialite'
      fullPath: '/acces-et-confidentialite'
      preLoaderRoute: typeof AccesEtConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/regarder/$slug': {
      id: '/regarder/$slug'
      path: '/regarder/$slug'
      fullPath: '/regarder/$slug'
      preLoaderRoute: typeof RegarderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titre/$slug': {
      id: '/titre/$slug'
      path: '/titre/$slug'
      fullPath: '/titre/$slug'
      preLoaderRoute: typeof TitreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/titres/$id': {
      id: '/_authenticated/admin/titres/$id'
      path: '/admin/titres/$id'
      fullPath: '/admin/titres/$id'
      preLoaderRoute: typeof AuthenticatedAdminTitresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTitresIdRoute: typeof AuthenticatedAdminTitresIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTitresIdRoute: AuthenticatedAdminTitresIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesEtConfidentialiteRoute: AccesEtConfidentialiteRoute,
  AuthRoute: AuthRoute,
  FilmsRoute: FilmsRoute,
  RechercheRoute: RechercheRoute,
  SeriesRoute: SeriesRoute,
  RegarderSlugRoute: RegarderSlugRoute,
  TitreSlugRoute: TitreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
